# Security settings for code execution
FORBIDDEN_STRINGS = [
    # Dangerous imports
    "import os",
    "import sys",
    "import subprocess",
    "import socket",
    "import pathlib",
    "import shutil",
    "import ctypes",
    "import resource",
    "import signal",
    "import inspect",
    "import importlib",
    "from os",
    "from sys",
    "from subprocess",
    "from socket",
    "from pathlib",
    "from shutil",
    "from ctypes",
    "from resource",
    "from signal",
    "from inspect",
    "from importlib",
    # Dangerous functions
    "eval(",
    "exec(",
    "compile(",
    "open(",
    "__import__",
    "input(",
    # Dangerous attribute access
    "getattr(",
    "setattr(",
    "delattr(",
    "globals()",
    "locals()",
    "vars()",
    "__class__",
    "__dict__",
    "__globals__",
    "__builtins__",
]
